builds:
- id: kubelet-csr-approver
  dir: .
  main: ./cmd/kubelet-csr-approver/
  env:
  - CGO_ENABLED=0
  ldflags:
  - -X github.com/postfinance/kubelet-csr-approver/internal/cmd.commit={{.Env.COMMIT}}
  - -X github.com/postfinance/kubelet-csr-approver/internal/cmd.ref={{.Env.REF}}
defaultBaseImage: ghcr.io/chainguard-images/static:latest

