name: Build and test

on:
  push:
    branches: ["*"]
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.17.x

      - run: |
          go build ./...
      
      - run: |
          go install sigs.k8s.io/controller-runtime/tools/setup-envtest@latest
          mkdir -p local/envtest-bin/
          setup-envtest use -p env 1.21.x --bin-dir local/envtest-bin > local/envtest-bin/env
      - run: |
          source local/envtest-bin/env
          export KUBEBUILDER_ASSETS=$(pwd)/$KUBEBUILDER_ASSETS
          go test -run=^$ ./...

