name: Test and publish

on:
  push:
    branches: ['main']

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.17
          stable: true

      - run: |
          go install sigs.k8s.io/controller-runtime/tools/setup-envtest@latest
          mkdir -p local/envtest-bin/
          setup-envtest use -p env 1.21.x --bin-dir local/envtest-bin > local/envtest-bin/env
      - name: Run Unit tests
        run: |
          source local/envtest-bin/env
          export KUBEBUILDER_ASSETS=$(pwd)/$KUBEBUILDER_ASSETS
          go test -race -covermode atomic -coverprofile=profile.cov ./...

      - name: Send coverage
        env:
          COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          go install github.com/mattn/goveralls@v0.0.11
          goveralls -coverprofile=profile.cov -service=github


  release-tagged:
    if: "startsWith(github.ref, 'refs/tags/v')"
    needs:
    # - lint
    - test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.17
          stable: true
            
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: postfinance
          password: ${{ secrets.DOCKER_TOKEN }}
      - uses: imjasonh/setup-ko@v0.4
        env:
          KO_DOCKER_REPO: docker.io/postfinance
      - run: |
          tag=$(echo ${{ github.ref }} | cut -d "/" -f 3 - ) 
          ko publish cmd/kubelet-csr-approver/ --base-import-paths --tags $tag
      
  release-untagged:
    if: "!startsWith(github.ref, 'refs/tags/v')"
    needs:
    # - lint
    - test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.17
          stable: true
            
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: postfinance
          password: ${{ secrets.DOCKER_TOKEN }}
      - uses: imjasonh/setup-ko@v0.4
        env:
          KO_DOCKER_REPO: docker.io/postfinance
      - run: |
          ko publish cmd/kubelet-csr-approver/ --base-import-paths 